name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: Pytest
        run: pytest -v -s
          